openai_api_key: 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
elevenlabs_api_key: 15dec7728128dcdc7254dcfa7c1ab947
greetings: |-
  I'm excited to meet you. I'm the OpenHome onboarding guide. Tell me what you're looking for and I'll customize the assistant to meet your personality